name: packer ami build deployment in AWS
on: 
  push:
    
jobs:
  packer-deploy:
    runs-on:  ubuntu-latest
    name: packer
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Clone our repository
        uses: actions/checkout@v2
      
      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::151926427169:role/github-actions-iodc
          aws-region: eu-west-1
          role-session-name: GithubPackerDeploy
      
      - name: Packer Set up
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: .pkr.hcl

      - name:  Packer initialization
        run:  packer init .

      - name: Packer planning
        run:  packer validate .

      - name: Packer applying
        run:  packer build .